name: Master

on:
  push:
    branches:
      - master

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: |
          cd ./apps/rsvp-frontend
          npm ci

      - name: Build
        run: |
          cd ./apps/rsvp-frontend
          npm run build
